FROM qt_base


#======================================
# Add ti-sdk
#======================================
# ADD ti-sdk-03.02.zip /opt

#======================================
# Settup workdir
#======================================
# WORKDIR /home/test

RUN mkdir /home/test/project

# VOLUME  ["/home/test/project"]