FROM qt_installer/finished


RUN wget http://software-dl.ti.com/processor-sdk-linux/esd/AM57X/03_02_00_05/exports/ti-processor-sdk-linux-am57xx-evm-03.02.00.05-Linux-x86-Install.bin 

RUN chmod +x ti-processor-sdk-linux-am57xx-evm-03.02.00.05-Linux-x86-Install.bin
CMD ./ti-processor-sdk-linux-am57xx-evm-03.02.00.05-Linux-x86-Install.bin
